packr/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from packr.database import (Column, Model, SurrogatePK, db, reference_col,
                            relationship)
from packr.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(254), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime,
                        nullable=False,
                        default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    is_business = Column(db.Boolean(), default=False)
    address = Column(db.String(300), nullable=True)
    phone = Column(db.String(16), nullable=True)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

packr/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(Form):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(),
                                    Email(),
                                    Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(),
                                         Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(),
                             EqualTo('password',
                                     message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

packr/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

packr/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user',
                      __name__,
                      url_prefix='/users',
                      static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

packr/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

packr/templates/footer.html
<footer class="page-footer purple lighten-2 white-text">
    <div class="container">
        <div class="col l9 s12">
            A Dirty Space Pirates Project.
        </div>
        <div class="col l3 s12">
            We might put something here later :)
        </div>
    </div>
</footer>

packr/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>{% block page_title %} Packr {% endblock %} </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}{% endblock %}">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
    {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% block css %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body class="{% block body_class %}{% endblock %}">
    {% block body %}
    {% with form=form  %}
    {% include "nav.html" %}
    {% endwith %}

    <header>{% block header %}{% endblock %}</header>
    {% block pre %} {%endblock%}
    <div class="{% block content_class %}container{% endblock content_class %}">

        <div role="main">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="row">
                <div class="col m12">
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                        {{message}}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
        </div>

    </div><!-- end container -->

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    {% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <script>
        {% block js %}{% endblock %}
    </script>
    <!-- end scripts -->
    {% endblock %}
</body>
</html>

packr/templates/nav.html
<nav class="white" role="navigation">
    <div class="nav-wrapper container">
        <a class="brand-logo" href="{{ url_for('public.home') }}">
            Packr
        </a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{{ url_for('public.home') }}">Home</a></li>
            <li><a href="{{ url_for('public.about') }}">About</a></li>
            {% if current_user and current_user.is_authenticated %}
                <li>
                    <a class="navbar-link" href="{{ url_for('user.members') }}">Logged in
                        as {{ current_user.username }}</a>
                </li>
                <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>
            {% else %}
                <li><a href="{{ url_for('public.register') }}">Create account</a></li>
                <li><a href="{{ url_for('public.login') }}">Login</a></li>
            {% endif %}
        </ul>
        <ul id="nav-mobile" class="side-nav">
            <li><a href="{{ url_for('public.home') }}">Home</a></li>
            <li><a href="{{ url_for('public.about') }}">About</a></li>
            {% if current_user and current_user.is_authenticated %}
                <li>
                    <p class="navbar-text">
                        <a class="navbar-link" href="{{ url_for('user.members') }}">
                            Logged in as {{ current_user.username }}
                        </a>
                    </p>
                </li>
                <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>
            {% else %}
                <li><a href="{{ url_for('public.register') }}">Create account</a></li>
                <li><a href="{{ url_for('public.login') }}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

packr/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}